---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '10'
  name: image-server
  namespace: '{{ .Values.global.xraylab.namespace }}'
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: image-server
  template:
    metadata:
      labels:
        app: image-server
    spec:
      containers:
      - env:
        - name: database-user
          valueFrom:
            secretKeyRef:
              key: database-user
              name: db-secret
        - name: database-password
          valueFrom:
            secretKeyRef:
              key: database-password
              name: db-secret
        - name: database-host
          valueFrom:
            secretKeyRef:
              key: database-host
              name: db-secret
        - name: database-db
          valueFrom:
            secretKeyRef:
              key: database-db
              name: db-secret
        - name: service_point
          valueFrom:
            configMapKeyRef:
              key: url-external
              name: service-point
        - name: bucket-base-name
          valueFrom:
            configMapKeyRef:
              key: bucket-base-name
              name: buckets-config
        image: image-server:latest
        imagePullPolicy: IfNotPresent
        name: image-server
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: '2'
            memory: 1G
          requests:
            cpu: 400m
            memory: 100M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

